### ISSUE TITLE
"Interface > Models > Adding External Model Paths" section is not optimal

### ISSUE THREAD

**Issue by darkeroticism** [Comfy-Org/docs#166]
[Interface > Models > Adding External Model Paths section](https://docs.comfy.org/development/core-concepts/models#adding-external-model-paths) is not optimal.

Currently, the following code is set.
```
additional_model_paths:
    animatediff_motion_lora: C:\Users\YourUsername\models\animatediff_motion_lora/
```

However, with this setting, it is registered in the model list in the sidebar, but it is not recognized as Lora and cannot be set. For example, it is not displayed as a LoRA option in the "Load LoRA" node. The same goes for the `checkpoints` file.

To solve this, you need to set it with property names such as `loras` and `checkpoints`. (example: `extra_model_paths.yaml`)

```yaml
comfyui_desktop:
# add setting
    loras: C:\Users\YourUsername\models\animatediff_motion_lora/
```
